type = "web_pixel_extension"
name = "atlas"
uid = "atlas-web-pixel-001"
runtime_context = "strict"

[customer_privacy]
analytics = true
marketing = false
preferences = false
sale_of_data = "disabled"

[build]
command = "npm run build"
watch = ["src/**/*"]

[capabilities]
network_calls = true

[settings]
type = "object"
fields = {}
