server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchwait: 1s
    batchsize: 1048576
    timeout: 10s

scrape_configs:
  # Scrape all Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Extract container name
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container"

      # Extract service label
      - source_labels: ["__meta_docker_container_label_service"]
        target_label: "service"

      # Extract compose project
      - source_labels:
          ["__meta_docker_container_label_com_docker_compose_project"]
        target_label: "compose_project"

      # Extract compose service
      - source_labels:
          ["__meta_docker_container_label_com_docker_compose_service"]
        target_label: "compose_service"

    pipeline_stages:
      # Extract log level if present
      - regex:
          expression: "(?i)(?P<level>debug|info|warn|warning|error|fatal|critical)"

      - labels:
          level:
