# Learn more about configuring your Customer account UI extension:
# https://shopify.dev/api/customer-account-ui-extensions/unstable/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-07"

[[extensions]]
name = "venus"
handle = "venus"
type = "ui_extension"
uid = "883039ef-d1b1-d011-d986-bea48c7c43777e121c7c"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/extension-targets-overview

# Order Status Page - Contextual cross-sell recommendations
[[extensions.targeting]]
module = "./src/OrderStatusBlock.tsx"
target = "customer-account.order-status.block.render"

# Order Index Page - Main recommendations hub
[[extensions.targeting]]
module = "./src/OrderIndexBlock.tsx"
target = "customer-account.order-index.block.render"

# Profile Page - Personalized recommendations
[[extensions.targeting]]
module = "./src/ProfileBlock.tsx"
target = "customer-account.profile.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/configuration#network-access
network_access = true


