app = "better-bundle"

[build]
  image = "better-bundle/gorse:latest"

[env]
  DATABASE_DSN = "{{ env \"DATABASE_DSN\" }}"
  REDIS_ENDPOINT = "{{ env \"REDIS_ENDPOINT\" }}"
  REDIS_PASSWORD = "{{ env \"REDIS_PASSWORD\" }}"

[[services]]
  internal_port = 8088
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443
