# Generated by Django 5.2.7 on 2025-10-22 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingTier",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("currency", models.CharField(max_length=3)),
                (
                    "trial_threshold_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "minimum_charge",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("proration_enabled", models.BooleanField(default=False)),
                ("tier_metadata", models.TextField(blank=True, null=True)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Pricing Tier",
                "verbose_name_plural": "Pricing Tiers",
                "db_table": "pricing_tiers",
                "ordering": ["subscription_plan", "currency"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("USAGE_BASED", "Usage Based"),
                            ("TIERED", "Tiered"),
                            ("FLAT_RATE", "Flat Rate"),
                            ("HYBRID", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "default_commission_rate",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("plan_metadata", models.TextField(blank=True, null=True)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "db_table": "subscription_plans",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShopSubscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRIAL", "Trial"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("TRIAL_COMPLETED", "Trial Completed"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="TRIAL",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_renew", models.BooleanField(default=True)),
                ("subscription_metadata", models.TextField(blank=True, null=True)),
                (
                    "user_chosen_cap_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pricing_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_subscriptions",
                        to="billing.pricingtier",
                    ),
                ),
                (
                    "shop",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_subscriptions",
                        to="shops.shop",
                    ),
                ),
                (
                    "subscription_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_subscriptions",
                        to="billing.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop Subscription",
                "verbose_name_plural": "Shop Subscriptions",
                "db_table": "shop_subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BillingInvoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("shopify_invoice_id", models.CharField(max_length=255, unique=True)),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=3)),
                ("invoice_date", models.DateTimeField()),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("OVERDUE", "Overdue"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                            ("FAILED", "Failed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("line_items", models.JSONField(blank=True, null=True)),
                ("shopify_response", models.JSONField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "failure_reason",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "shop_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_invoices",
                        to="billing.shopsubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Invoice",
                "verbose_name_plural": "Billing Invoices",
                "db_table": "billing_invoices",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="BillingCycle",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("cycle_number", models.IntegerField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "initial_cap_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "current_cap_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "usage_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("commission_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cycle_metadata", models.TextField(blank=True, null=True)),
                (
                    "shop_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_cycles",
                        to="billing.shopsubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Cycle",
                "verbose_name_plural": "Billing Cycles",
                "db_table": "billing_cycles",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="subscription_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing_tiers",
                to="billing.subscriptionplan",
            ),
        ),
    ]
