"""Baseline schema

Adopts Alembic on an already-running database.

The schema up to this point was created by `Base.metadata.create_all()` at
startup, so there is no migration history to reconstruct. This revision
therefore establishes the current models as the baseline:

  - On a FRESH database it creates everything, so `alembic upgrade head` is all
    that is needed to stand one up.
  - On an EXISTING database, run `alembic stamp 0001_baseline` instead. That
    records the revision as applied without executing it, because the tables
    are already there.

Every migration after this one is autogenerated with explicit operations. This
is the only one that leans on metadata, and it does so deliberately: hand-
writing 21 tables' worth of DDL that already exists would be a large diff with
nothing to verify it against.

Revision ID: 0001_baseline
Revises: None
Create Date: 2026-09-08
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401  (registers the Vector type)

from app.core.database.models import Base

revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# `product_vectors.vector` is a pgvector column, so the type must exist before
# any table referencing it is created.
REQUIRED_EXTENSIONS = ("vector",)


def upgrade() -> None:
    bind = op.get_bind()

    for ext in REQUIRED_EXTENSIONS:
        op.execute(f'CREATE EXTENSION IF NOT EXISTS "{ext}"')

    # checkfirst=True so this is safe to run against a partially-populated
    # database, which is the realistic state of any environment predating
    # Alembic here.
    Base.metadata.create_all(bind=bind, checkfirst=True)


def downgrade() -> None:
    # Dropping every table is not a useful reverse for a baseline — it would
    # destroy all merchant data to undo "we started tracking migrations".
    raise NotImplementedError(
        "The baseline revision cannot be downgraded. To reset a development "
        "database use `python -m app.core.database.create_tables drop`."
    )
