"""fx rates for multi-currency billing

Revision ID: e03a08987227
Revises: df36dc8a8857
Create Date: 2026-09-09 16:31:02.043618
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = 'e03a08987227'
down_revision: Union[str, None] = 'df36dc8a8857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('usd_rate', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_rates_currency'), 'exchange_rates', ['currency'], unique=True)
    op.add_column('commission_records', sa.Column('source_currency', sa.String(length=3), nullable=True, comment='Currency the attributed revenue was measured in'))
    op.add_column('commission_records', sa.Column('fx_rate', sa.Numeric(precision=20, scale=10), nullable=True, comment='Units of source_currency per 1 USD used for this commission'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commission_records', 'fx_rate')
    op.drop_column('commission_records', 'source_currency')
    op.drop_index(op.f('ix_exchange_rates_currency'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
