"""order attribution state for bounded reconciliation

Revision ID: 2e4b4f530eae
Revises: e03a08987227
Create Date: 2026-09-10 07:23:50.892793
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '2e4b4f530eae'
down_revision: Union[str, None] = 'e03a08987227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_data', sa.Column('attribution_state', sa.String(length=20), nullable=True))
    op.add_column('order_data', sa.Column('attribution_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('order_data', sa.Column('attribution_last_error', sa.Text(), nullable=True))
    op.create_index('ix_order_data_attribution_pending', 'order_data', ['order_date'], unique=False, postgresql_where=sa.text("attribution_state = 'pending'"))
    # ### end Alembic commands ###

    # Backfill. Orders already in the table were written before the column
    # existed, so every one of them reads NULL — meaning "nothing to attribute".
    # Without this the reconciler would be permanently blind to any order that
    # was already stamped but never attributed, which is exactly the population
    # it exists to rescue.
    #
    # This is the one place the expensive jsonb scan is acceptable: it runs once,
    # not every fifteen minutes. Doing it now is also far cheaper than it will
    # ever be again — at a hundred orders it is instant, at millions of line
    # items it would need an online batched backfill.
    #
    # Anything already attributed is marked 'done' rather than 'pending', so the
    # reconciler does not immediately republish the entire order history.
    op.execute(
        """
        UPDATE order_data o
        SET attribution_state = CASE
                WHEN EXISTS (
                    SELECT 1 FROM purchase_attributions pa
                    WHERE pa.shop_id = o.shop_id AND pa.order_id = o.order_id
                ) THEN 'done'
                ELSE 'pending'
            END
        WHERE EXISTS (
            SELECT 1 FROM line_item_data l
            WHERE l.order_id = o.id
              AND l.properties::jsonb ? '_bb_rec_impression_id'
        )
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_data_attribution_pending', table_name='order_data', postgresql_where=sa.text("attribution_state = 'pending'"))
    op.drop_column('order_data', 'attribution_last_error')
    op.drop_column('order_data', 'attribution_attempts')
    op.drop_column('order_data', 'attribution_state')
    # ### end Alembic commands ###
