"""payg pricing: commission records, rate/cap/threshold

Revision ID: 342208096fc9
Revises: 0001_baseline
Create Date: 2026-09-08 15:59:32.713971
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '342208096fc9'
down_revision: Union[str, None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_records',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('shop_id', sa.String(length=255), nullable=False),
    sa.Column('purchase_attribution_id', sa.String(length=255), nullable=False),
    sa.Column('billing_cycle_id', sa.String(length=255), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attributed_revenue', sa.Numeric(precision=10, scale=2), nullable=False, comment='Total attributed revenue from the purchase'),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=4), nullable=False, comment='Commission rate (e.g., 0.03 for 3%)'),
    sa.Column('commission_earned', sa.Numeric(precision=10, scale=2), nullable=False, comment='Full commission amount (attributed_revenue * rate)'),
    sa.Column('commission_charged', sa.Numeric(precision=10, scale=2), nullable=False, comment='Actual amount charged to Shopify (may be partial or 0 during trial)'),
    sa.Column('commission_overflow', sa.Numeric(precision=10, scale=2), nullable=False, comment="Amount that couldn't be charged due to cap"),
    sa.Column('billing_cycle_start', sa.DateTime(timezone=True), nullable=True, comment='Start of the 30-day billing cycle'),
    sa.Column('billing_cycle_end', sa.DateTime(timezone=True), nullable=True, comment='End of the 30-day billing cycle'),
    sa.Column('cycle_usage_before', sa.Numeric(precision=10, scale=2), nullable=False, comment='Cycle usage before this commission'),
    sa.Column('cycle_usage_after', sa.Numeric(precision=10, scale=2), nullable=False, comment='Cycle usage after this commission'),
    sa.Column('capped_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Maximum amount that can be charged in this cycle'),
    sa.Column('trial_accumulated', sa.Numeric(precision=10, scale=2), nullable=False, comment='Accumulated trial revenue at time of this commission'),
    sa.Column('billing_phase', sa.Enum('TRIAL', 'PAID', name='billing_phase_enum'), nullable=False, comment='Whether this is trial or paid phase'),
    sa.Column('status', sa.Enum('TRIAL_PENDING', 'TRIAL_COMPLETED', 'PENDING', 'RECORDED', 'INVOICED', 'REJECTED', 'FAILED', 'CAPPED', name='commission_status_enum'), nullable=False, comment='Current status of commission'),
    sa.Column('charge_type', sa.Enum('FULL', 'PARTIAL', 'OVERFLOW_ONLY', 'TRIAL', 'REJECTED', name='charge_type_enum'), nullable=False, comment='Type of charge (full, partial, etc.)'),
    sa.Column('shopify_usage_record_id', sa.String(length=255), nullable=True, comment='Shopify usage record GID if sent to Shopify'),
    sa.Column('shopify_recorded_at', sa.DateTime(timezone=True), nullable=True, comment='When the usage was recorded to Shopify'),
    sa.Column('shopify_response', sa.JSON(), nullable=True, comment='Response from Shopify API'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Currency code (ISO 4217)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes or reasons'),
    sa.Column('commission_metadata', sa.JSON(), nullable=True, comment='Additional metadata'),
    sa.Column('error_count', sa.Integer(), nullable=False, comment='Number of failed attempts to charge'),
    sa.Column('last_error', sa.Text(), nullable=True, comment='Last error message if failed'),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True, comment='When the last error occurred'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"), nullable=False),
    sa.ForeignKeyConstraint(['billing_cycle_id'], ['billing_cycles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_attribution_id'], ['purchase_attributions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_attribution_id', name='uq_commission_purchase_attribution')
    )
    op.create_index('idx_commission_shop_cycle', 'commission_records', ['shop_id', 'billing_cycle_start', 'billing_cycle_end'], unique=False)
    op.create_index('idx_commission_shop_phase_status', 'commission_records', ['shop_id', 'billing_phase', 'status'], unique=False)
    op.create_index('idx_commission_shopify_record', 'commission_records', ['shopify_usage_record_id'], unique=False)
    op.create_index('idx_commission_status_created', 'commission_records', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_commission_records_billing_cycle_end'), 'commission_records', ['billing_cycle_end'], unique=False)
    op.create_index(op.f('ix_commission_records_billing_cycle_id'), 'commission_records', ['billing_cycle_id'], unique=False)
    op.create_index(op.f('ix_commission_records_billing_cycle_start'), 'commission_records', ['billing_cycle_start'], unique=False)
    op.create_index(op.f('ix_commission_records_billing_phase'), 'commission_records', ['billing_phase'], unique=False)
    op.create_index(op.f('ix_commission_records_deleted_at'), 'commission_records', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_commission_records_order_date'), 'commission_records', ['order_date'], unique=False)
    op.create_index(op.f('ix_commission_records_order_id'), 'commission_records', ['order_id'], unique=False)
    op.create_index(op.f('ix_commission_records_purchase_attribution_id'), 'commission_records', ['purchase_attribution_id'], unique=True)
    op.create_index(op.f('ix_commission_records_shop_id'), 'commission_records', ['shop_id'], unique=False)
    op.create_index(op.f('ix_commission_records_shopify_usage_record_id'), 'commission_records', ['shopify_usage_record_id'], unique=True)
    op.create_index(op.f('ix_commission_records_status'), 'commission_records', ['status'], unique=False)
    op.add_column('shop_subscriptions', sa.Column('commission_rate_override', sa.Numeric(precision=5, scale=4), nullable=True, comment='Override commission rate (from subscription_plan.commission_rate)'))
    op.add_column('shop_subscriptions', sa.Column('cap_amount_override', sa.Numeric(precision=10, scale=2), nullable=True, comment='Override monthly cap, e.g. after the merchant approves a raise'))
    op.add_column('shop_subscriptions', sa.Column('trial_threshold_override', sa.Numeric(precision=10, scale=2), nullable=True, comment='Override free attributed revenue before the first charge'))
    op.drop_column('shop_subscriptions', 'monthly_fee_override')
    op.add_column('subscription_plans', sa.Column('commission_rate', sa.Numeric(precision=5, scale=4), server_default='0.0300', nullable=False, comment='Share of attributed revenue charged, e.g. 0.0300 = 3%'))
    op.add_column('subscription_plans', sa.Column('cap_amount', sa.Numeric(precision=10, scale=2), server_default='299.00', nullable=False, comment='Maximum chargeable per 30-day cycle (Shopify cappedAmount)'))
    op.add_column('subscription_plans', sa.Column('trial_revenue_threshold', sa.Numeric(precision=10, scale=2), server_default='1000.00', nullable=False, comment='Attributed revenue earned free before the first charge'))
    op.alter_column('subscription_plans', 'trial_days',
               existing_type=sa.INTEGER(),
               comment='Backstop trial expiry, so an unused install does not stay open forever',
               existing_comment='Number of free trial days before first charge',
               existing_nullable=True)
    op.drop_column('subscription_plans', 'monthly_fee')
    op.drop_column('subscription_plans', 'discount_percentage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('discount_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True, comment='Promotional discount percentage applied to monthly_fee (e.g. 50.00 = 50% off)'))
    op.add_column('subscription_plans', sa.Column('monthly_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Full monthly fee charged via Shopify AppSubscription'))
    op.alter_column('subscription_plans', 'trial_days',
               existing_type=sa.INTEGER(),
               comment='Number of free trial days before first charge',
               existing_comment='Backstop trial expiry, so an unused install does not stay open forever',
               existing_nullable=True)
    op.drop_column('subscription_plans', 'trial_revenue_threshold')
    op.drop_column('subscription_plans', 'cap_amount')
    op.drop_column('subscription_plans', 'commission_rate')
    op.add_column('shop_subscriptions', sa.Column('monthly_fee_override', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Override monthly fee for this shop (from subscription_plan.monthly_fee)'))
    op.drop_column('shop_subscriptions', 'trial_threshold_override')
    op.drop_column('shop_subscriptions', 'cap_amount_override')
    op.drop_column('shop_subscriptions', 'commission_rate_override')
    op.drop_index(op.f('ix_commission_records_status'), table_name='commission_records')
    op.drop_index(op.f('ix_commission_records_shopify_usage_record_id'), table_name='commission_records')
    op.drop_index(op.f('ix_commission_records_shop_id'), table_name='commission_records')
    op.drop_index(op.f('ix_commission_records_purchase_attribution_id'), table_name='commission_records')
    op.drop_index(op.f('ix_commission_records_order_id'), table_name='commission_records')
    op.drop_index(op.f('ix_commission_records_order_date'), table_name='commission_records')
    op.drop_index(op.f('ix_commission_records_deleted_at'), table_name='commission_records')
    op.drop_index(op.f('ix_commission_records_billing_phase'), table_name='commission_records')
    op.drop_index(op.f('ix_commission_records_billing_cycle_start'), table_name='commission_records')
    op.drop_index(op.f('ix_commission_records_billing_cycle_id'), table_name='commission_records')
    op.drop_index(op.f('ix_commission_records_billing_cycle_end'), table_name='commission_records')
    op.drop_index('idx_commission_status_created', table_name='commission_records')
    op.drop_index('idx_commission_shopify_record', table_name='commission_records')
    op.drop_index('idx_commission_shop_phase_status', table_name='commission_records')
    op.drop_index('idx_commission_shop_cycle', table_name='commission_records')
    op.drop_table('commission_records')
    # ### end Alembic commands ###
