"""shops: database defaults for boolean flags

Revision ID: 31380aa88a4b
Revises: 342208096fc9
Create Date: 2026-09-08 16:18:28.661962
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '31380aa88a4b'
down_revision: Union[str, None] = '342208096fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shops', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=False)
    op.alter_column('shops', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False)
    op.alter_column('shops', 'setup_guide_visited',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False)
    op.alter_column('shops', 'shopify_plus',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False)
    op.alter_column('shops', 'holdout_disabled',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shops', 'holdout_disabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shops', 'shopify_plus',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shops', 'setup_guide_visited',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shops', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shops', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
