"""product_enrichments: durable LLM enrichment state with retry

Revision ID: ce4b52bddb76
Revises: 16d1aa12da39
Create Date: 2026-09-08 17:06:22.731401
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = 'ce4b52bddb76'
down_revision: Union[str, None] = '16d1aa12da39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_enrichments',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', name='enrichment_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('text_hash', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False, comment='Failed attempts so far; at MAX_ENRICHMENT_ATTEMPTS it is a dead letter'),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_attempt_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('succeeded_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('shop_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'product_id', name='uq_product_enrichment_shop_product')
    )
    op.create_index('idx_product_enrichments_retryable', 'product_enrichments', ['shop_id', 'status', 'attempts'], unique=False)
    op.create_index(op.f('ix_product_enrichments_product_id'), 'product_enrichments', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_enrichments_shop_id'), 'product_enrichments', ['shop_id'], unique=False)
    op.create_index(op.f('ix_product_enrichments_status'), 'product_enrichments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_enrichments_status'), table_name='product_enrichments')
    op.drop_index(op.f('ix_product_enrichments_shop_id'), table_name='product_enrichments')
    op.drop_index(op.f('ix_product_enrichments_product_id'), table_name='product_enrichments')
    op.drop_index('idx_product_enrichments_retryable', table_name='product_enrichments')
    op.drop_table('product_enrichments')
    # ### end Alembic commands ###
