"""drop day-based trial: trial ends on attributed revenue only

Revision ID: 16d1aa12da39
Revises: 31380aa88a4b
Create Date: 2026-09-08 16:31:30.419085
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '16d1aa12da39'
down_revision: Union[str, None] = '31380aa88a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_subscriptions', 'trial_duration_days')
    op.drop_column('subscription_plans', 'trial_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('trial_days', sa.INTEGER(), autoincrement=False, nullable=True, comment='Backstop trial expiry, so an unused install does not stay open forever'))
    op.add_column('shop_subscriptions', sa.Column('trial_duration_days', sa.INTEGER(), autoincrement=False, nullable=True, comment='Override trial duration in days (from subscription_plan.trial_days)'))
    # ### end Alembic commands ###
