# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "87c44f5966daa80691a480bcd03c225c"
name = "BetterBundle"
application_url = "https://betterbundle.site"
embedded = true
handle = "better-bundle-1"

[webhooks]
api_version = "2024-07"

[[webhooks.subscriptions]]
topics = ["customers/update"]
uri = "/webhooks/customers/update"

[[webhooks.subscriptions]]
topics = ["refunds/create"]
uri = "/webhooks/refunds/create"

[[webhooks.subscriptions]]
topics = ["orders/edited"]
uri = "/webhooks/orders/edited"

[[webhooks.subscriptions]]
topics = ["collections/create"]
uri = "/webhooks/collections/create"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
topics = ["collections/delete"]
uri = "/webhooks/collections/delete"

[[webhooks.subscriptions]]
topics = ["products/create"]
uri = "/webhooks/products/create"

[[webhooks.subscriptions]]
topics = ["app_subscriptions/update"]
uri = "/webhooks/billing/subscription_update"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["collections/update"]
uri = "/webhooks/collections/update"

[[webhooks.subscriptions]]
topics = ["customers/create"]
uri = "/webhooks/customers/create"

[[webhooks.subscriptions]]
topics = ["orders/paid"]
uri = "/webhooks/orders/paid"

[[webhooks.subscriptions]]
topics = ["products/delete"]
uri = "/webhooks/products/delete"

[[webhooks.subscriptions]]
topics = ["inventory_levels/update"]
uri = "/webhooks/inventory_levels/update"

[[webhooks.subscriptions]]
topics = ["app_subscriptions/approaching_capped_amount"]
uri = "/webhooks/billing/approaching_cap"

[[webhooks.subscriptions]]
topics = ["products/update"]
uri = "/webhooks/products/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_custom_pixels,read_customer_data_erasure,read_customer_events,read_customers,read_draft_orders,read_files,read_inventory,read_locations,read_markets,read_metaobject_definitions,read_metaobjects,read_order_edits,read_orders,read_pixels,read_products,read_publications,read_returns,read_themes,write_custom_pixels,write_customer_data_erasure,write_customers,write_draft_orders,write_files,write_inventory,write_locations,write_markets,write_metaobject_definitions,write_metaobjects,write_order_edits,write_orders,write_pixels,write_products,write_publications,write_returns,write_themes"

[auth]
redirect_urls = [
  "https://betterbundle.site/auth/callback",
  "https://betterbundle.site/auth/shopify/callback",
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
