# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "87c44f5966daa80691a480bcd03c225c"
name = "BetterBundle"
application_url = "https://namibia-nokia-internet-secretariat.trycloudflare.com"
embedded = true
handle = "better-bundle-1"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true


[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  topics = [ "collections/update" ]
  uri = "/webhooks/collections/update"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/webhooks/products/delete"

  [[webhooks.subscriptions]]
  topics = [ "customers/update" ]
  uri = "/webhooks/customers/update"

  [[webhooks.subscriptions]]
  topics = [ "customers/create" ]
  uri = "/webhooks/customers/create"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "collections/create" ]
  uri = "/webhooks/collections/create"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/products/create"

  [[webhooks.subscriptions]]
  topics = [ "collections/delete" ]
  uri = "/webhooks/collections/delete"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

  [[webhooks.subscriptions]]
  topics = [ "orders/edited" ]
  uri = "/webhooks/orders/edited"

  [[webhooks.subscriptions]]
  topics = [ "refunds/create" ]
  uri = "/webhooks/refunds/create"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

  [[webhooks.subscriptions]]
  topics = [ "inventory_levels/update" ]
  uri = "/webhooks/inventory_levels/update"


[[webhooks.subscriptions]]
topics = [ "app_subscriptions/update" ]
uri = "/webhooks/billing/subscription_update"

[[webhooks.subscriptions]]
topics = [ "app_subscriptions/approaching_capped_amount" ]
uri = "/webhooks/billing/approaching_cap"

#[[webhooks.subscriptions]]
#topics = [ "subscription_billing_attempts/success" ]
#uri = "/webhooks/billing/billing_success"

#[[webhooks.subscriptions]]
#topics = [ "subscription_billing_attempts/failure" ]
#uri = "/webhooks/billing/billing_failed"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_content,read_customer_events,read_customers,read_discounts,read_inventory,read_locales,read_marketing_events,read_orders,read_pixels,read_products,read_returns,read_themes,write_pixels,write_products"

[auth]
redirect_urls = [

]

[pos]
embedded = false
