# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "67ed7387b7e177679b747bf339bf739e"
name = "Better-Bundle-Dev"
application_url = "https://1a53-223-184-242-150.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/refunds/create"
  topics = [ "refunds/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/billing/approaching_cap"
  topics = [ "app_subscriptions/approaching_capped_amount" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/paid"
  topics = [ "orders/paid" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/collections/create"
  topics = [ "collections/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/update"
  topics = [ "products/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/collections/delete"
  topics = [ "collections/delete" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/create"
  topics = [ "products/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/inventory_levels/update"
  topics = [ "inventory_levels/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/billing/subscription_update"
  topics = [ "app_subscriptions/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/create"
  topics = [ "customers/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/update"
  topics = [ "customers/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/delete"
  topics = [ "products/delete" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/updated"
  topics = [ "orders/updated" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/collections/update"
  topics = [ "collections/update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_data_erasure,read_customers,read_draft_orders,read_files,read_inventory,read_locations,read_markets,read_metaobject_definitions,read_metaobjects,read_order_edits,read_orders,read_products,read_publications,read_returns,read_themes,write_customer_data_erasure,write_customers,write_draft_orders,write_files,write_inventory,write_locations,write_markets,write_metaobject_definitions,write_metaobjects,write_order_edits,write_orders,write_products,write_publications,write_returns,write_themes"

[auth]
redirect_urls = [
  "https://1a53-223-184-242-150.ngrok-free.app/auth/callback",
  "https://1a53-223-184-242-150.ngrok-free.app/auth/shopify/callback"
]

[pos]
embedded = false
