name = "better-bundle-ml-api"
main = "main.py"
compatibility_date = "2024-01-01"

[env.production]
name = "better-bundle-ml-api-prod"
route = "ml-api.yourdomain.com/*"
zone_id = "your-zone-id"

[env.development]
name = "better-bundle-ml-api-dev"
route = "dev-ml-api.yourdomain.com/*"
zone_id = "your-zone-id"

[build]
command = "pip install -r requirements.txt"

[build.upload]
format = "service-worker"

[env.production.vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "https://your-shopify-app.vercel.app"

[env.development.vars]
ENVIRONMENT = "development"
CORS_ORIGIN = "https://dev-your-shopify-app.vercel.app"

# Free tier limits
[env.production.limits]
cpu_ms = 50
memory_mb = 128

[env.development.limits]
cpu_ms = 50
memory_mb = 128
