# Generated by Django 5.2.7 on 2025-10-22 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseAttribution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("session_id", models.CharField(db_index=True, max_length=255)),
                ("order_id", models.CharField(db_index=True, max_length=255)),
                ("contributing_extensions", models.JSONField()),
                ("attribution_weights", models.JSONField()),
                ("total_revenue", models.DecimalField(decimal_places=2, max_digits=10)),
                ("attributed_revenue", models.JSONField()),
                ("total_interactions", models.IntegerField()),
                ("interactions_by_extension", models.JSONField()),
                ("purchase_at", models.DateTimeField(db_index=True)),
                ("attribution_algorithm", models.CharField(max_length=50)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_attributions",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Attribution",
                "verbose_name_plural": "Purchase Attributions",
                "db_table": "purchase_attributions",
                "ordering": ["-purchase_at"],
            },
        ),
        migrations.CreateModel(
            name="CommissionRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("order_id", models.CharField(db_index=True, max_length=255)),
                ("order_date", models.DateTimeField(db_index=True)),
                (
                    "attributed_revenue",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                (
                    "commission_earned",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "commission_charged",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "commission_overflow",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("billing_cycle_start", models.DateTimeField(blank=True, null=True)),
                ("billing_cycle_end", models.DateTimeField(blank=True, null=True)),
                (
                    "cycle_usage_before",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "cycle_usage_after",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("capped_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "trial_accumulated",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "billing_phase",
                    models.CharField(
                        choices=[("TRIAL", "Trial"), ("PAID", "Paid")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRIAL_PENDING", "Trial Pending"),
                            ("TRIAL_COMPLETED", "Trial Completed"),
                            ("PENDING", "Pending"),
                            ("RECORDED", "Recorded"),
                            ("INVOICED", "Invoiced"),
                            ("REJECTED", "Rejected"),
                            ("FAILED", "Failed"),
                            ("CAPPED", "Capped"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Full"),
                            ("PARTIAL", "Partial"),
                            ("OVERFLOW_ONLY", "Overflow Only"),
                            ("TRIAL", "Trial"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "shopify_usage_record_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("shopify_recorded_at", models.DateTimeField(blank=True, null=True)),
                ("shopify_response", models.JSONField(blank=True, null=True)),
                ("currency", models.CharField(max_length=3)),
                ("notes", models.TextField(blank=True, null=True)),
                ("commission_metadata", models.JSONField(blank=True, null=True)),
                ("error_count", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "billing_cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_records",
                        to="billing.billingcycle",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_records",
                        to="shops.shop",
                    ),
                ),
                (
                    "purchase_attribution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_record",
                        to="revenue.purchaseattribution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commission Record",
                "verbose_name_plural": "Commission Records",
                "db_table": "commission_records",
                "ordering": ["-order_date"],
            },
        ),
    ]
