"""
Application-level constants
"""

# Application Information
PROJECT_NAME = "BetterBundle Python Worker"
VERSION = "1.0.0"
API_VERSION = "v1"

# Environment
ENVIRONMENT_DEVELOPMENT = "development"
ENVIRONMENT_STAGING = "staging"
ENVIRONMENT_PRODUCTION = "production"

# HTTP Status Codes
HTTP_OK = 200
HTTP_CREATED = 201
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_INTERNAL_SERVER_ERROR = 500

# Time Constants
SECONDS_PER_MINUTE = 60
MINUTES_PER_HOUR = 60
HOURS_PER_DAY = 24
SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR
SECONDS_PER_DAY = SECONDS_PER_HOUR * HOURS_PER_DAY

# Default Values
DEFAULT_PORT = 8001
DEFAULT_WORKER_ID = "python-worker-1"
DEFAULT_WORKER_CONCURRENCY = 4
DEFAULT_BATCH_SIZE = 3
DEFAULT_POLLING_INTERVAL_MS = 30000
DEFAULT_IDLE_SLEEP_SECONDS = 10
DEFAULT_ERROR_SLEEP_SECONDS = 15

# Health Check
HEALTH_CHECK_TIMEOUT = 5
HEALTH_CHECK_INTERVAL = 30

__all__ = [
    "PROJECT_NAME",
    "VERSION", 
    "API_VERSION",
    "ENVIRONMENT_DEVELOPMENT",
    "ENVIRONMENT_STAGING",
    "ENVIRONMENT_PRODUCTION",
    "HTTP_OK",
    "HTTP_CREATED",
    "HTTP_BAD_REQUEST",
    "HTTP_UNAUTHORIZED",
    "HTTP_FORBIDDEN",
    "HTTP_NOT_FOUND",
    "HTTP_INTERNAL_SERVER_ERROR",
    "SECONDS_PER_MINUTE",
    "MINUTES_PER_HOUR",
    "HOURS_PER_DAY",
    "SECONDS_PER_HOUR",
    "SECONDS_PER_DAY",
    "DEFAULT_PORT",
    "DEFAULT_WORKER_ID",
    "DEFAULT_WORKER_CONCURRENCY",
    "DEFAULT_BATCH_SIZE",
    "DEFAULT_POLLING_INTERVAL_MS",
    "DEFAULT_IDLE_SLEEP_SECONDS",
    "DEFAULT_ERROR_SLEEP_SECONDS",
    "HEALTH_CHECK_TIMEOUT",
    "HEALTH_CHECK_INTERVAL",
]
