"""
Redis-specific constants
"""

DEFAULT_REDIS_PORT = 6379
DEFAULT_REDIS_DB = 0
DEFAULT_REDIS_TLS = True
DEFAULT_REDIS_TIMEOUT = 60
DEFAULT_REDIS_HEALTH_CHECK_INTERVAL = 30

# Redis Stream Configuration
DEFAULT_STREAM_MAX_LEN = 1000
DEFAULT_STREAM_APPROX_MAX_LEN = True
DEFAULT_STREAM_IDLE_TIME = 300000  # 5 minutes in milliseconds

__all__ = [
    "DEFAULT_REDIS_PORT",
    "DEFAULT_REDIS_DB",
    "DEFAULT_REDIS_TLS",
    "DEFAULT_REDIS_TIMEOUT",
    "DEFAULT_REDIS_HEALTH_CHECK_INTERVAL",
    "DEFAULT_STREAM_MAX_LEN",
    "DEFAULT_STREAM_APPROX_MAX_LEN",
    "DEFAULT_STREAM_IDLE_TIME",
]
