"""
Shopify constants for BetterBundle Python Worker
"""

# Shopify API endpoints
SHOPIFY_API_VERSION = "2024-01"
SHOPIFY_API_BASE_URL = "https://{shop}.myshopify.com/admin/api/{version}"

# Shopify data collection limits
SHOPIFY_MAX_PRODUCTS_PER_REQUEST = 250
SHOPIFY_MAX_ORDERS_PER_REQUEST = 250
SHOPIFY_MAX_CUSTOMERS_PER_REQUEST = 250
SHOPIFY_MAX_COLLECTIONS_PER_REQUEST = 250

# Shopify webhook topics
SHOPIFY_WEBHOOK_TOPICS = [
    "products/create",
    "products/update",
    "products/delete",
    "orders/create",
    "orders/updated",
    "orders/paid",
    "orders/fulfilled",
    "customers/create",
    "customers/update",
    "customers/delete",
    "collections/create",
    "collections/update",
    "collections/delete",
]

# Shopify data types
SHOPIFY_ENTITY_TYPES = [
    "shop",
    "product",
    "order",
    "customer",
    "collection",
    "line_item",
    "customer_event",
]

# Shopify field mappings
SHOPIFY_FIELD_MAPPINGS = {
    "product": [
        "id",
        "title",
        "body_html",
        "vendor",
        "product_type",
        "tags",
        "status",
        "published_at",
        "created_at",
        "updated_at",
        "handle",
        "published_scope",
        "admin_graphql_api_id",
    ],
    "order": [
        "id",
        "email",
        "closed_at",
        "created_at",
        "updated_at",
        "number",
        "note",
        "token",
        "gateway",
        "test",
        "total_price",
        "subtotal_price",
        "total_weight",
        "total_tax",
        "taxes_included",
        "currency",
        "financial_status",
        "confirmed",
        "total_discounts",
        "total_line_items_price",
        "cart_token",
        "buyer_accepts_marketing",
        "name",
        "referring_site",
        "landing_site",
        "cancelled_at",
        "cancel_reason",
        "total_price_usd",
        "checkout_token",
        "reference",
        "user_id",
        "location_id",
        "source_identifier",
        "source_url",
        "processed_at",
        "device_id",
        "phone",
        "customer_locale",
        "app_id",
        "browser_ip",
        "landing_site_ref",
        "order_number",
        "discount_applications",
        "discount_codes",
        "note_attributes",
        "payment_gateway_names",
        "processing_method",
        "checkout_id",
        "source_name",
        "fulfillment_status",
        "tax_lines",
        "tags",
        "contact_email",
        "order_status_url",
        "presentment_currency",
        "total_line_items_price_set",
        "total_discounts_set",
        "total_shipping_price_set",
        "subtotal_price_set",
        "total_price_set",
        "total_tax_set",
        "line_items",
        "shipping_lines",
        "billing_address",
        "shipping_address",
        "fulfillments",
        "client_details",
        "refunds",
        "customer",
        "shipping_lines",
        "billing_address",
        "shipping_address",
    ],
    "customer": [
        "id",
        "email",
        "accepts_marketing",
        "created_at",
        "updated_at",
        "first_name",
        "last_name",
        "orders_count",
        "state",
        "total_spent",
        "last_order_id",
        "note",
        "verified_email",
        "multipass_identifier",
        "tax_exempt",
        "phone",
        "tags",
        "last_order_name",
        "currency",
        "addresses",
        "accepts_marketing_updated_at",
        "marketing_opt_in_level",
        "tax_exemptions",
        "admin_graphql_api_id",
        "default_address",
    ],
    "collection": [
        "id",
        "handle",
        "title",
        "updated_at",
        "body_html",
        "published_at",
        "sort_order",
        "published_scope",
        "admin_graphql_api_id",
    ],
}

__all__ = [
    "SHOPIFY_API_VERSION",
    "SHOPIFY_API_BASE_URL",
    "SHOPIFY_MAX_PRODUCTS_PER_REQUEST",
    "SHOPIFY_MAX_ORDERS_PER_REQUEST",
    "SHOPIFY_MAX_CUSTOMERS_PER_REQUEST",
    "SHOPIFY_MAX_COLLECTIONS_PER_REQUEST",
    "SHOPIFY_WEBHOOK_TOPICS",
    "SHOPIFY_ENTITY_TYPES",
    "SHOPIFY_FIELD_MAPPINGS",
]
