# Generated by Django 5.2.7 on 2025-10-22 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "shop_domain",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "custom_domain",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("access_token", models.CharField(max_length=1000)),
                (
                    "plan_type",
                    models.CharField(db_index=True, default="Free", max_length=50),
                ),
                (
                    "currency_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "money_format",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("shopify_plus", models.BooleanField(db_index=True, default=False)),
                (
                    "suspended_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "suspension_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "service_impact",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "last_analysis_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Shop",
                "verbose_name_plural": "Shops",
                "db_table": "shops",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductData",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("product_id", models.CharField(db_index=True, max_length=255)),
                ("title", models.CharField(max_length=500)),
                ("handle", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "product_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("vendor", models.CharField(blank=True, max_length=255, null=True)),
                ("tags", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("total_inventory", models.IntegerField(blank=True, null=True)),
                ("price", models.FloatField()),
                ("compare_at_price", models.FloatField(blank=True, null=True)),
                ("price_range", models.JSONField(blank=True, null=True)),
                ("collections", models.JSONField(blank=True, null=True)),
                ("seo_title", models.CharField(blank=True, max_length=500, null=True)),
                ("seo_description", models.TextField(blank=True, null=True)),
                (
                    "template_suffix",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("variants", models.JSONField(blank=True, null=True)),
                ("images", models.JSONField(blank=True, null=True)),
                ("media", models.JSONField(blank=True, null=True)),
                ("options", models.JSONField(blank=True, null=True)),
                ("metafields", models.JSONField(blank=True, null=True)),
                ("extras", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_data",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "product_data",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderData",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("order_id", models.CharField(db_index=True, max_length=255)),
                ("order_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "customer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "customer_display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customer_state",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("customer_verified_email", models.BooleanField(blank=True, null=True)),
                ("customer_default_address", models.JSONField(blank=True, null=True)),
                ("total_amount", models.FloatField()),
                ("subtotal_amount", models.FloatField(blank=True, null=True)),
                ("total_tax_amount", models.FloatField(blank=True, null=True)),
                ("total_shipping_amount", models.FloatField(blank=True, null=True)),
                ("total_refunded_amount", models.FloatField(blank=True, null=True)),
                ("total_outstanding_amount", models.FloatField(blank=True, null=True)),
                ("order_date", models.DateTimeField(db_index=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancel_reason",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "order_locale",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "currency_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "presentment_currency_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("confirmed", models.BooleanField(default=False)),
                ("test", models.BooleanField(default=False)),
                (
                    "financial_status",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "fulfillment_status",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("tags", models.JSONField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("note_attributes", models.JSONField(blank=True, null=True)),
                ("shipping_address", models.JSONField(blank=True, null=True)),
                ("billing_address", models.JSONField(blank=True, null=True)),
                ("discount_applications", models.JSONField(blank=True, null=True)),
                ("metafields", models.JSONField(blank=True, null=True)),
                ("fulfillments", models.JSONField(blank=True, null=True)),
                ("transactions", models.JSONField(blank=True, null=True)),
                ("extras", models.JSONField(blank=True, null=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_data",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "order_data",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="CustomerData",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("customer_id", models.CharField(db_index=True, max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("total_spent", models.FloatField()),
                ("order_count", models.IntegerField()),
                ("last_order_date", models.DateTimeField(blank=True, null=True)),
                (
                    "last_order_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("verified_email", models.BooleanField()),
                ("tax_exempt", models.BooleanField()),
                (
                    "customer_locale",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("tags", models.JSONField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("default_address", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField()),
                ("extras", models.JSONField(blank=True, null=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_data",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "db_table": "customer_data",
                "ordering": ["-created_at"],
            },
        ),
    ]
