import { BACKEND_URL } from "../config/constants";

// JWT Token Management
interface TokenInfo {
  token: string;
  expiresIn: number;
  shopDomain: string;
  shopStatus: string;
  permissions: string[];
}

class JWTManager {
  private TOKEN_KEY = "betterbundle_jwt_token";
  private TOKEN_EXPIRY_KEY = "betterbundle_jwt_expiry";
  private SHOP_DOMAIN_KEY = "betterbundle_shop_domain";
  private refreshPromise: Promise<TokenInfo> | null = null;

  constructor(private sessionStorage: any) {
    // Store sessionStorage for JWT operations
  }

  async getValidToken(
    shopDomain: string,
    customerId?: string | null,
  ): Promise<string | null> {
    const storedToken = await this.getStoredToken();

    // Use cached token if valid
    if (
      storedToken &&
      storedToken.token &&
      storedToken.shopDomain === shopDomain &&
      this.isTokenNotExpired(storedToken)
    ) {
      return storedToken.token;
    }

    // Fetch new token
    try {
      return await this.refreshToken(shopDomain, customerId);
    } catch (error) {
      return null;
    }
  }

  private async refreshToken(
    shopDomain: string,
    customerId?: string | null,
  ): Promise<string | null> {
    if (this.refreshPromise) {
      try {
        return (await this.refreshPromise).token;
      } catch (error) {
        return null;
      }
    }

    this.refreshPromise = this.fetchNewToken(shopDomain, customerId);

    try {
      const tokenInfo = await this.refreshPromise;
      await this.storeToken(tokenInfo);
      return tokenInfo.token;
    } catch (error) {
      return null;
    } finally {
      this.refreshPromise = null;
    }
  }

  private async fetchNewToken(
    shopDomain: string,
    customerId?: string | null,
  ): Promise<TokenInfo> {
    const requestBody: any = { shop_domain: shopDomain };

    if (customerId) {
      requestBody.customer_id = customerId;
    }

    const response = await fetch(`${BACKEND_URL}/api/v1/auth/shop-token`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      throw new Error(`Token generation failed: ${response.status}`);
    }

    const data = await response.json();
    return {
      token: data.token,
      expiresIn: data.expires_in,
      shopDomain: data.shop_domain,
      shopStatus: data.shop_status,
      permissions: data.permissions,
    };
  }

  private isTokenNotExpired(tokenInfo: TokenInfo): boolean {
    if (!tokenInfo || !tokenInfo.expiresIn) return false;
    const now = Date.now() / 1000;
    const expiry = tokenInfo.expiresIn;
    return expiry - now > 60; // Valid if expires in more than 1 minute
  }

  private async getStoredToken(): Promise<TokenInfo | null> {
    try {
      const token = await this.sessionStorage.getItem(this.TOKEN_KEY);
      const shopDomain = await this.sessionStorage.getItem(
        this.SHOP_DOMAIN_KEY,
      );

      if (!token || !shopDomain) return null;

      return {
        token,
        expiresIn: parseInt(
          (await this.sessionStorage.getItem(this.TOKEN_EXPIRY_KEY)) || "0",
        ),
        shopDomain,
        shopStatus: "unknown",
        permissions: [],
      };
    } catch (error) {
      return null;
    }
  }

  private async storeToken(tokenInfo: TokenInfo): Promise<void> {
    try {
      await this.sessionStorage.setItem(this.TOKEN_KEY, tokenInfo.token);
      const expiryTimestamp =
        Math.floor(Date.now() / 1000) + tokenInfo.expiresIn;
      await this.sessionStorage.setItem(
        this.TOKEN_EXPIRY_KEY,
        expiryTimestamp.toString(),
      );
      await this.sessionStorage.setItem(
        this.SHOP_DOMAIN_KEY,
        tokenInfo.shopDomain,
      );
    } catch (error) {
      // Silently fail
    }
  }

  async makeAuthenticatedRequest(
    url: string,
    options: RequestInit = {},
  ): Promise<Response> {
    // We need shopDomain and customerId to be passed in, but for now return a basic response
    // This will be updated when we integrate it properly
    return fetch(url, {
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

/**
 * Get unified browser session ID (shared across ALL extensions)
 * This should match the ID generated by Phoenix/Apollo
 */
const getBrowserSessionId = async (sessionStorage: any): Promise<string> => {
  let sessionId = await sessionStorage.getItem("unified_browser_session_id");
  if (!sessionId) {
    sessionId =
      "unified_" + Date.now() + "_" + Math.random().toString(36).substr(2, 9);
    await sessionStorage.setItem("unified_browser_session_id", sessionId);
  }
  return sessionId;
};

/**
 * Get or store Shopify client ID in sessionStorage
 * This allows other extensions to access it
 */
const getOrStoreClientId = async (
  sessionStorage: any,
  clientId: string | null,
): Promise<string | null> => {
  // Try to get existing client_id from sessionStorage
  let storedClientId = await sessionStorage.getItem("unified_client_id");

  // If we have a new client_id from event and it's different, update it
  if (clientId && clientId !== storedClientId) {
    await sessionStorage.setItem("unified_client_id", clientId);
    console.log(
      "📱 Atlas: Stored client_id in sessionStorage:",
      clientId.substring(0, 16) + "...",
    );
    return clientId;
  }

  // Return stored one if available
  return storedClientId || clientId;
};

let sessionCreationPromise: Promise<string> | null = null;

/**
 * Get or create a session for Atlas tracking
 */
export const getOrCreateSession = async (
  shopDomain: string,
  userAgent: string,
  customerId: string | null,
  pageUrl: string,
  referrer: string,
  sessionStorage: any,
  clientId: string,
): Promise<string> => {
  const storedClientId = await getOrStoreClientId(sessionStorage, clientId);

  // ✅ STEP 2: Check if we have a valid cached session
  const storedSessionId = await sessionStorage.getItem("unified_session_id");
  const storedExpiresAt = await sessionStorage.getItem(
    "unified_session_expires_at",
  );

  if (
    storedSessionId &&
    storedExpiresAt &&
    Date.now() < parseInt(storedExpiresAt)
  ) {
    console.log("⚡ Atlas: Reusing cached session:", storedSessionId);

    // ✅ IMPORTANT: If we have a NEW client_id, update backend in background
    if (clientId && clientId !== storedClientId) {
      console.log("🔄 Atlas: Updating client_id in background");
      updateClientIdInBackground(
        storedSessionId,
        clientId,
        shopDomain,
        sessionStorage,
        customerId,
      ).catch((err) => {
        console.warn("⚠️ Failed to update client_id in background:", err);
      });
    }

    return storedSessionId;
  }

  // ✅ STEP 3: Check if another Atlas call is already creating a session (race condition prevention)
  if (sessionCreationPromise) {
    console.log("🔒 Atlas: Session creation already in progress, waiting...");
    return await sessionCreationPromise;
  }

  sessionCreationPromise = (async () => {
    try {
      const jwtManager = new JWTManager(sessionStorage);
      const token = await jwtManager.getValidToken(shopDomain, customerId);

      const url = `${BACKEND_URL}/api/atlas/get-or-create-session`;
      const browserSessionId = await getBrowserSessionId(sessionStorage);

      const payload = {
        shop_domain: shopDomain,
        customer_id: customerId,
        browser_session_id: browserSessionId,
        client_id: storedClientId || clientId, // Use latest available
        user_agent: userAgent,
        ip_address: null, // Will be detected server-side
        referrer: referrer,
        page_url: pageUrl,
      };

      const response = await fetch(url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          ...(token && { Authorization: `Bearer ${token}` }),
        },
        body: JSON.stringify(payload),
        keepalive: true,
      });

      if (!response.ok) {
        if (response.status === 403) {
          throw new Error("Services suspended");
        }
        throw new Error(`Session creation failed: ${response.status}`);
      }

      const result = await response.json();

      if (result.success && result.data && result.data.session_id) {
        const sessionId = result.data.session_id;
        const expiresAt = Date.now() + 30 * 60 * 1000; // 30 minutes from now

        // Store session data in sessionStorage for persistence (unified across all extensions)
        await sessionStorage.setItem("unified_session_id", sessionId);
        await sessionStorage.setItem(
          "unified_session_expires_at",
          expiresAt.toString(),
        );

        // ✅ NEW: Store backend's client_id if returned
        if (result.data.client_id) {
          await sessionStorage.setItem(
            "unified_client_id",
            result.data.client_id,
          );
        }

        return sessionId;
      } else {
        throw new Error(result.message || "Failed to create session");
      }
    } catch (error) {
      throw error;
    } finally {
      sessionCreationPromise = null;
    }
  })();
  return await sessionCreationPromise;
};

/**
 * Track interaction using unified analytics
 */
export const trackInteraction = async (
  event: any,
  shopDomain: string,
  userAgent: string,
  customerId: string | null,
  interactionType: string,
  pageUrl: string,
  referrer: string,
  sessionStorage: any,
  sendBeacon: any,
): Promise<void> => {
  try {
    const clientId = event?.clientId || null;

    const sessionId = await getOrCreateSession(
      shopDomain,
      userAgent,
      customerId,
      pageUrl,
      referrer,
      sessionStorage,
      clientId,
    );

    const jwtManager = new JWTManager(sessionStorage);
    const token = await jwtManager.getValidToken(shopDomain, customerId);

    const interactionData = {
      session_id: sessionId,
      shop_domain: shopDomain,
      customer_id: customerId,
      interaction_type: interactionType,
      metadata: {
        ...event,
      },
    };

    // Send to unified analytics endpoint
    const url = `${BACKEND_URL}/api/atlas/track-interaction`;

    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...(token && { Authorization: `Bearer ${token}` }),
      },
      body: JSON.stringify(interactionData),
      keepalive: true,
    });

    if (!response.ok) {
      if (response.status === 403) {
        throw new Error("Services suspended");
      }
      throw new Error(`Interaction tracking failed: ${response.status}`);
    }

    const result = await response.json();

    // Handle session recovery if it occurred
    if (result.session_recovery) {
      console.log("🔄 Atlas: Session recovered:", result.session_recovery);
      // Update stored session ID with the new one (unified with other extensions)
      await sessionStorage.setItem(
        "unified_session_id",
        result.session_recovery.new_session_id,
      );
    }
  } catch (error) {
    throw error;
  }
};

const updateClientIdInBackground = async (
  sessionId: string,
  clientId: string,
  shopDomain: string,
  sessionStorage?: any,
  customerId?: string | null,
): Promise<void> => {
  try {
    const url = `${BACKEND_URL}/api/session/update-client-id`;

    let token: string | null = null;
    if (sessionStorage) {
      const jwtManager = new JWTManager(sessionStorage);
      token = await jwtManager.getValidToken(shopDomain, customerId);
    }

    await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...(token && { Authorization: `Bearer ${token}` }),
      },
      body: JSON.stringify({
        session_id: sessionId,
        client_id: clientId,
        shop_domain: shopDomain,
      }),
      keepalive: true,
    });

    console.log("✅ Atlas: client_id updated in background");
  } catch (error) {
    console.warn("⚠️ Atlas: Background client_id update failed:", error);
    // Don't throw - this is non-critical
  }
};
