# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "BetterBundle"
client_id = "87c44f5966daa80691a480bcd03c225c"
application_url = "https://gdp-buffer-stood-raises.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_orders"

[auth]
redirect_urls = ["https://gdp-buffer-stood-raises.trycloudflare.com/auth/callback", "https://gdp-buffer-stood-raises.trycloudflare.com/auth/shopify/callback", "https://gdp-buffer-stood-raises.trycloudflare.com/api/auth/callback"]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "vnsaid.myshopify.com"
include_config_on_deploy = true
