# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "87c44f5966daa80691a480bcd03c225c"
name = "BetterBundle"
application_url = "https://sure-hardcover-demographic-observer.trycloudflare.com"
embedded = true
handle = "better-bundle-1"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "vnsaid.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_content,read_customers,read_discounts,read_inventory,read_locales,read_marketing_events,read_orders,read_price_rules,read_products,read_script_tags,read_themes,write_content,write_customers,write_discounts,write_inventory,write_locales,write_marketing_events,write_orders,write_price_rules,write_products,write_script_tags,write_themes"

[auth]
redirect_urls = ["https://sure-hardcover-demographic-observer.trycloudflare.com/auth/callback", "https://sure-hardcover-demographic-observer.trycloudflare.com/auth/shopify/callback", "https://sure-hardcover-demographic-observer.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
