# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "87c44f5966daa80691a480bcd03c225c"
name = "BetterBundle"
application_url = "https://namibia-nokia-internet-secretariat.trycloudflare.com"
embedded = true
handle = "better-bundle-1"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "vnsaid.myshopify.com"

[webhooks]
api_version = "2024-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_content,read_customers,read_discounts,read_inventory,read_locales,read_marketing_events,read_orders,read_products,read_themes,write_products,write_pixels,read_customer_events"

[auth]
redirect_urls = ["https://namibia-nokia-internet-secretariat.trycloudflare.com/auth/callback", "https://namibia-nokia-internet-secretariat.trycloudflare.com/auth/shopify/callback", "https://namibia-nokia-internet-secretariat.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
