# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "BetterBundle"
client_id = "87c44f5966daa80691a480bcd03c225c"
application_url = "https://betterbundle.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_orders,write_app_events"

[auth]
redirect_urls = [
  "https://betterbundle.vercel.app/auth/callback",
  "https://betterbundle.vercel.app/auth/shopify/callback",
  "https://betterbundle.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "vnsaid.myshopify.com"
include_config_on_deploy = true
