[database]
# Cache store for Upstash Redis (will be overridden by GORSE_CACHE_STORE env var)
cache_store = ""

# Data store for Render PostgreSQL (will be overridden by GORSE_DATA_STORE env var)
data_store = ""

[master]
host = "0.0.0.0"
port = 8086
http_port = 8088

[server]
http_port = 8088

[recommend.data_source]
# The feedback types for positive events.
positive_feedback_types = ["star","like"]

# The feedback types for read events.
read_feedback_types = ["read"]
