services:
  redis:
    image: redis/redis-stack:7.2.0-v18
    restart: unless-stopped
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gorse
      POSTGRES_USER: gorse
      POSTGRES_PASSWORD: gorse_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  worker:
    image: zhenghaoz/gorse-worker:nightly
    restart: unless-stopped
    depends_on:
      - master
    env_file:
      - local.env

  server:
    image: zhenghaoz/gorse-server:nightly
    restart: unless-stopped
    ports:
      - "8087:8087"
    depends_on:
      - master
    env_file:
      - local.env

  master:
    image: zhenghaoz/gorse-master:nightly
    restart: unless-stopped
    ports:
      - "8086:8086"
      - "8088:8088"
    env_file:
      - local.env
    volumes:
      - ./config/config.toml:/etc/gorse/config.toml
    depends_on:
      - redis
      - postgres

volumes:
  postgres_data:
