services:
  gorse-worker:
    image: zhenghaoz/gorse-worker:latest
    restart: unless-stopped
    ports:
      - "8089:8089"
    command: >
      --master-host gorse-master --master-port 8086 
      --http-host 0.0.0.0 --http-port 8089
      --log-path /var/log/gorse/worker.log 
      --cache-path /var/lib/gorse/worker_cache.data
    volumes:
      - gorse_log:/var/log/gorse
      - worker_data:/var/lib/gorse
    depends_on:
      - gorse-master
    networks:
      - gorse-network
    environment:
      - GORSE_LOG_LEVEL=info

  gorse-server:
    image: zhenghaoz/gorse-server:latest
    restart: unless-stopped
    ports:
      - "8087:8087"
    command: >
      --master-host gorse-master --master-port 8086 
      --http-host 0.0.0.0 --http-port 8087
      --log-path /var/log/gorse/server.log 
      --cache-path /var/lib/gorse/server_cache.data
    volumes:
      - gorse_log:/var/log/gorse
      - server_data:/var/lib/gorse
    depends_on:
      - gorse-master
    networks:
      - gorse-network
    environment:
      - GORSE_LOG_LEVEL=info

  gorse-master:
    image: zhenghaoz/gorse-master:latest
    restart: unless-stopped
    ports:
      - "8086:8086"
      - "8088:8088"
    environment:
      # Database connections - will be overridden by env vars
      GORSE_CACHE_STORE: ${GORSE_CACHE_STORE}
      GORSE_DATA_STORE: ${GORSE_DATA_STORE}
      GORSE_LOG_LEVEL: info
      # Production settings
      GORSE_MASTER_HOST: 0.0.0.0
      GORSE_MASTER_PORT: 8086
      GORSE_MASTER_HTTP_PORT: 8088
    command: >
      -c /etc/gorse/config.toml 
      --log-path /var/log/gorse/master.log 
      --cache-path /var/lib/gorse
    volumes:
      - ./config/config.production.toml:/etc/gorse/config.toml
      - gorse_log:/var/log/gorse
      - master_data:/var/lib/gorse
      # Mount host DNS resolver to fix external hostname resolution
      - /etc/resolv.conf:/etc/resolv.conf:ro
    networks:
      - gorse-network
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  worker_data:
  server_data:
  master_data:
  gorse_log:

networks:
  gorse-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
