name: Daily Billing Settlement

on:
  # schedule:
  #   # Run daily at 2 AM UTC
  #   - cron: "0 2 * * *"

  # Allow manual trigger
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run (no actual charges)"
        required: false
        default: "false"

jobs:
  settle-billing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run daily settlement
        run: |
          echo "🚀 Starting daily billing settlement..."
          curl -X POST "${{ secrets.API_URL }}/api/billing/settle?dry_run=${{ github.event.inputs.dry_run || 'false' }}" \
            -H "X-Cron-Secret: ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            --max-time 1800 \
            --retry 3 \
            --retry-delay 10

      - name: Notify on failure
        if: failure()
        run: |
          echo "Settlement failed! Check logs."
          # Add Slack/email notification here
