name: Monthly Billing Processing

on:
  schedule:
    # Run on the 1st of every month at 2:00 AM UTC
    - cron: "0 2 1 * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  process-monthly-billing:
    runs-on: ubuntu-latest

    steps:
      - name: Process Monthly Billing
        run: |
          echo "Processing monthly billing for all shops..."

          # Get the current date for logging
          echo "Date: $(date)"
          echo "Processing billing for previous month..."

          # Make HTTP request to the billing cron endpoint
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET_TOKEN }}" \
            -H "Content-Type: application/json" \
            "${{ secrets.APP_URL }}/api/cron/monthly-billing" \
            -w "\nHTTP Status: %{http_code}\nResponse Time: %{time_total}s\n"

          echo "Monthly billing processing completed!"

        env:
          CRON_SECRET_TOKEN: ${{ secrets.CRON_SECRET_TOKEN }}
          APP_URL: ${{ secrets.APP_URL }}

      - name: Notify on Success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: success
          channel: "#billing"
          text: "✅ Monthly billing processed successfully!"

      - name: Notify on Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          channel: "#billing"
          text: "❌ Monthly billing processing failed!"
