name: Monthly Billing Job

on:
  schedule:
    # Run every day at 2:00 AM UTC (cron format)
    - cron: "0 2 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  monthly-billing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd python-worker
          pip install -r requirements.txt

      - name: Run monthly billing
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
          SHOPIFY_API_SECRET: ${{ secrets.SHOPIFY_API_SECRET }}
        run: |
          cd python-worker
          python run_monthly_billing.py

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Monthly billing job failed. Check the logs for details.'
            })
